server:
  port: 8622
  servlet:
    session:
      timeout: 7200
  tomcat:
    # 默认是200
    threads:
      max: 5 #减少tomcat线程数

spring:
  application:
    name: Caddy&NginxGUI
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  jackson:
    default-property-inclusion: NON_NULL
  jmx:
    enabled: true
  database:
    type: sqlite
    package: com.cym.model
    print: true
    sqlite-path: ${project.home}sqlite.db

project:
  version: v@project.version@
  home: /home/nginxWebUI/

logging:
  file:
    name: ${project.home}log/Caddy&NginxGUI.log
  level:
    root: info
